#!/bin/bash
#
# cvnsnapper-plain-backingstorage - btrfs backing storage
# Copyright (C) 2017  Fabian Pietsch <fabian@canvon.de>

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"
	exit 1
}


USAGE="cvnsnapper-plain-backingstorage show BTRFS_MOUNT_POINT"

while [ "$#" -gt 0 ] && [ "${1:0:1}" = "-" ]
do
	OPTION="$1"
	shift

	case "$OPTION" in
	--help|--usage|-\?)
		echo "Usage: $USAGE"
		exit 0
		;;
	*)
		die "Invalid option \"$OPTION\""
		;;
	esac
done

[ "$#" -ge 1 ] || die "Usage: $USAGE"

MODE="$1"
shift

case "$MODE" in
show)
	die "Mode-of-operation \"$MODE\": Not implemented, yet."
	;;
*)
	die "Invalid mode-of-operation \"$MODE\""
	;;
esac

exit 0
