#!/bin/bash

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"
	exit 1
}


USAGE="Usage: $0 OUTPUT_PREFIX [START_SNAPSHOT_NUMBER]"

while [ "$#" -ge 1 ] && [ "${1:0:1}" = "-" ]
do
	case "$1" in
	--help|--usage)
		shift
		echo "$USAGE"
		exit 0
		;;
	*)
		die "Invalid option \"$1\""
		;;
	esac
done

[ "$#" -ge 1 ] || die "$USAGE"

OUTPUT_PREFIX="$1"; shift
START_SNAPSHOT_NUMBER=

[ "$#" -ge 1 ] && { START_SNAPSHOT_NUMBER="$1"; shift; }

[ "$#" -eq 0 ] || die "Too many arguments -- $USAGE"


while read SNAPSHOT_NUMBER
do
	# Skip snapshots silently until start, if start was given.
	[ -n "$START_SNAPSHOT_NUMBER" ] && [ "$SNAPSHOT_NUMBER" -lt "$START_SNAPSHOT_NUMBER"] && continue

	echo -n "snapper snapshot number $SNAPSHOT_NUMBER: "

	SNAPSHOT_INFO="$SNAPSHOT_NUMBER/info.xml"
	if ! [ -f "$SNAPSHOT_INFO" ]
	then
		echo "No info.xml, skipped."
		warn "Skipping snapper snapshot number $SNAPSHOT_NUMBER due to missing info.xml!"
		continue
	fi

	SNAPSHOT_CLEANUP=$(sed -n -e 's#^.*<cleanup>\([^<]*\)</cleanup>.*#\1#p' <"$SNAPSHOT_INFO") || { echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER cleanup policy: sed failed"; }
	if [ "$SNAPSHOT_CLEANUP" = "timeline" ]
	then
		echo "cleanup policy \"$SNAPSHOT_CLEANUP\", skipped."
		continue
	fi

	echo "Would btrfs send, but not implemented, yet"
done < <(ls -1d [1-9]* | sort -n)

exit 0
