#!/bin/bash

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"
	exit 1
}


INFIX=
DIFF_INFIX=
DIFF_SUBVOL=
DIFF_MODE=
DIFF_ONLY=

# Change defaults based on what we were called as.
case "${0##*/}" in
*-diff*)
	USAGE="Usage: $0 [--diff-subvol=DIFF_SUBVOL] [--diff-infix=DIFF_INFIX] [--infix=INFIX] SUBVOL [...]"
	DIFF_ONLY=1
	;;
*)
	USAGE="Usage: $0 [--diff-only] [--diff-subvol=DIFF_SUBVOL] [--diff-infix=DIFF_INFIX] [--infix=INFIX] SUBVOL [...]"
	;;
esac

while [ "$#" -ge 1 ] && [ "${1:0:1}" = "-" ]
do
	case "$1" in
	--help|--usage)
		shift
		echo "$USAGE"
		exit 0
		;;
	--infix=*)
		INFIX=${1#--infix=}
		shift
		echo "Using infix \"$INFIX\""
		;;
	--diff-infix=*)
		DIFF_INFIX=${1#--diff-infix=}
		DIFF_MODE=1
		shift
		echo "Will diff against infix \"$DIFF_INFIX\""
		;;
	--diff-subvol=*)
		DIFF_SUBVOL=${1#--diff-subvol=}
		DIFF_MODE=1
		shift
		echo "Will diff against subvol \"$DIFF_SUBVOL\""
		;;
	--diff-only)
		DIFF_ONLY=1
		shift
		echo "Diff-only mode"
		;;
	-*)
		die "Unrecognized option \"$1\""
		;;
	esac
done

[ "$#" -ge 1 ] || die "$USAGE"

if [ -n "$DIFF_MODE" ] || [ -n "$DIFF_ONLY" ]
then
	[ -z "$DIFF_SUBVOL" ] && [ "$DIFF_INFIX" = "$INFIX" ] && die "Syntax error: Diff mode requested, but infixes are the same -- diff infix \"$DIFF_INFIX\" vs. infix \"$INFIX\""
fi


get-stat-device() {
	# Stream Editor:
	# * Instead of in filter mode, run in explicit output mode.
	#   (no print, -n)
	# * On first line beginning with "Device:", operate and,
	#   in any case, quit. (/.../ { ...; q })
	# * Try to extract the device string (hex/dec), by matching
	#   on the whole line and replacing it by the group-matched
	#   device string. If successful, output.
	#   (s/.../.../p, substitute & print)
	sed -n -e '/^Device:/ { s/^Device: \([^[:space:]]*\)[[:space:]]\+.*/\1/p; q }'
}

adjust-stat-device() {
	[ "$#" -eq 2 ] || die "Internal error: adjust-stat-device usage: ADJUST_STAT_DEVICE_FROM ADJUST_STAT_DEVICE_TO"
	local ADJUST_STAT_DEVICE_FROM="$1" ADJUST_STAT_DEVICE_TO="$2"
	shift 2
	if [ -n "$ADJUST_STAT_DEVICE_FROM" ] && [ -n "$ADJUST_STAT_DEVICE_TO" ] &&
	   ! [ "$ADJUST_STAT_DEVICE_FROM" = "$ADJUST_STAT_DEVICE_TO" ]
	then
		sed -e "/^Device:/ s#$ADJUST_STAT_DEVICE_FROM#$ADJUST_STAT_DEVICE_TO#"
	else
		# Degrade to "filter" as-is.
		cat
	fi
}

sort-stat() {
	# Perl:
	# * Use slurp mode.
	# * Read in entire data.
	# * Split into records at line beginnings that contain a file name,
	#   using a zero-width look-ahead so the match won't be removed.
	# * Sort records by string comparison and output the results.
	#   As they should all begin with "  File:", this should effectively
	#   sort by file name.
	# * Let's hope that this won't explode on big (several hundreds of MiB?
	#   or even larger?) input data.
	perl -e 'undef $/; my $data = <>; my @records = split(/^(?=  File:)/m, $data); print sort { $a cmp $b } @records'
}


RET=0

for SUBVOL
do
	# (In diff-only mode, don't require the subvolume to actually be there;
	# this allows operating just on the meta-data.)
	if [ -z "$DIFF_ONLY" ]
	then
		[ -d "$SUBVOL" ] || die "Not a directory: $SUBVOL"

		[ "$(stat --format="%i" "$SUBVOL")" -eq 256 ] || die "Not a btrfs subvolume: $SUBVOL"
	fi


	export SUBVOL_STAT_LOG="${SUBVOL}${INFIX}.stat.log"
	export SUBVOL_CHECKSUMS_FILE="${SUBVOL}${INFIX}.sha256"

	if [ -n "$DIFF_ONLY" ]
	then
		# In diff-only mode, require the files to be already there.
		# Check will be done while diffing, below.
		:
	else
		[ -e "$SUBVOL_STAT_LOG" ] && die "Stat log file for btrfs subvolume \"$SUBVOL\" already exists: $SUBVOL_STAT_LOG"
		[ -e "$SUBVOL_CHECKSUMS_FILE" ] && die "Checksums file for btrfs subvolume \"$SUBVOL\" already exists: $SUBVOL_CHECKSUMS_FILE"

		exec {SUBVOL_STAT_LOG_FD}>>"$SUBVOL_STAT_LOG" || die "Couldn't open stat log file for btrfs subvolume \"$SUBVOL\": $SUBVOL_STAT_LOG"
		export SUBVOL_STAT_LOG_FD

		exec {SUBVOL_CHECKSUMS_FILE_FD}>>"$SUBVOL_CHECKSUMS_FILE" || die "Couldn't open checksums file for btrfs subvolume \"$SUBVOL\": $SUBVOL_CHECKSUMS_FILE"
		export SUBVOL_CHECKSUMS_FILE_FD 


		echo
		echo "Processing btrfs subvolume $SUBVOL ..."

		( cd "$SUBVOL" && find \
			! -path . -inum 256 -printf "Pruning child subvolume %p\n" -prune , \
			-type f -exec bash -c "sha256sum --binary -- \"\$@\" >&\"\$SUBVOL_CHECKSUMS_FILE_FD\"" checksums "{}" + , \
			-exec bash -c "stat -- \"\$@\" >&\"\$SUBVOL_STAT_LOG_FD\"" stat-log "{}" +
		) || die "Subshell with cd and find exited unsuccessfully (with exit code $?)"
	fi


	if [ -n "$DIFF_MODE" ] || [ -n "$DIFF_ONLY" ]
	then
		echo
		echo "Diffing meta-data of subvol \"$SUBVOL\" from${DIFF_SUBVOL:+ diff subvol \"$DIFF_SUBVOL\"} infix \"$DIFF_INFIX\" to infix \"$INFIX\"..."

		DIFF_RESULT=0

		SUBVOL_STAT_LOG_PREV="${DIFF_SUBVOL:-$SUBVOL}${DIFF_INFIX}.stat.log"
		SUBVOL_CHECKSUMS_FILE_PREV="${DIFF_SUBVOL:-$SUBVOL}${DIFF_INFIX}.sha256"

		if ! [ -f "$SUBVOL_CHECKSUMS_FILE_PREV" ]
		then
			warn "Warning: Checksums can't be diff'ed for subvol \"$SUBVOL\": Previous checksums file missing or not a regular file: $SUBVOL_CHECKSUMS_FILE_PREV"
			[ "$RET" -lt 2 ] && RET=2
			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
		elif ! [ -f "$SUBVOL_CHECKSUMS_FILE" ]
		then
			warn "Warning: Checksums can't be diff'ed for subvol \"$SUBVOL\": Later checksums file missing or not a regular file: $SUBVOL_CHECKSUMS_FILE"
			[ "$RET" -lt 2 ] && RET=2
			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
		else
			echo "Diffing checksums:"
			if ! diff <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE_PREV") <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE")
			then
				warn "Warning: Checksum differences found for subvol \"$SUBVOL\", from infix \"$DIFF_INFIX\" to infix \"$INFIX\""
				[ "$RET" -lt 1 ] && RET=1
				[ "$DIFF_RESULT" -lt 1 ] && DIFF_RESULT=1
			fi
		fi

		if ! [ -f "$SUBVOL_STAT_LOG_PREV" ]
		then
			warn "Warning: Stat results can't be diff'ed for subvol \"$SUBVOL\": Previous stat log missing or not a regular file: $SUBVOL_STAT_LOG_PREV"
			[ "$RET" -lt 2 ] && RET=2
			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
		elif ! [ -f "$SUBVOL_STAT_LOG" ]
		then
			warn "Warning: Stat results can't be diff'ed for subvol \"$SUBVOL\": Later stat log missing or not a regular file: $SUBVOL_STAT_LOG"
			[ "$RET" -lt 2 ] && RET=2
			[ "$DIFF_RESULT" -lt 2 ] && DIFF_RESULT=2
		else
			SRC_DEVICE="$(get-stat-device <"$SUBVOL_STAT_LOG_PREV")" || SRC_DEVICE=
			DST_DEVICE="$(get-stat-device <"$SUBVOL_STAT_LOG")"      || DST_DEVICE=
			ADJUSTED=
			[ "$SRC_DEVICE" != "$DST_DEVICE" ] && ADJUSTED=1

			echo "Diffing stat results${ADJUSTED:+, adjusted}:"
			if ! diff -U8 \
				<(sort-stat <"$SUBVOL_STAT_LOG_PREV" | adjust-stat-device "$SRC_DEVICE" "$DST_DEVICE") \
				<(sort-stat <"$SUBVOL_STAT_LOG")
			then
				warn "Warning: stat differences found for subvol \"$SUBVOL\", from infix \"$DIFF_INFIX\" to infix \"$INFIX\""
				[ "$RET" -lt 1 ] && RET=1
				[ "$DIFF_RESULT" -lt 1 ] && DIFF_RESULT=1
			fi
		fi

		echo -n "Overall diff result: "
		case "$DIFF_RESULT" in
		0)
			echo "Success; no differences found."
			;;
		1)
			echo "Soft failure; some differences found."
			;;
		2)
			echo "Hard failure; e.g., some meta-data files were missing."
			;;
		*)
			echo "(unknown)"
			;;
		esac
	fi


	# (In diff-only mode, don't close the fds as they have not been opened.)
	if [ -z "$DIFF_ONLY" ]
	then
		exec {SUBVOL_CHECKSUMS_FILE_FD}>&- || die "Couldn't close checksums file for btrfs subvolume \"$SUBVOL\": $SUBVOL_CHECKSUMS_FILE"
		exec {SUBVOL_STAT_LOG_FD}>&- || die "Couldn't close stat log file for btrfs subvolume \"$SUBVOL\": $SUBVOL_STAT_LOG"
	fi

	unset SUBVOL_CHECKSUMS_FILE_FD SUBVOL_CHECKSUMS_FILE
	unset SUBVOL_STAT_LOG_FD SUBVOL_STAT_LOG
done

if [ "$RET" -ne 0 ]
then
	warn "Warning: Exiting unsuccessfully (with exit code $RET)"
else
	echo
	echo "Summary: No problems detected."
fi

exit "$RET"
