#!/bin/bash

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"
	exit 1
}


INFIX=
DIFF_INFIX=

USAGE="Usage: $0 [--infix=INFIX] SUBVOL [...]"

[ "$#" -ge 1 ] || die "$USAGE"

while [ "$#" -ge 1 ] && [ "${1:0:1}" = "-" ]
do
	case "$1" in
	--help|--usage)
		shift
		echo "$USAGE"
		exit 0
		;;
	--infix=*)
		INFIX=${1#--infix=}
		shift
		echo "Using infix \"$INFIX\""
		;;
	--diff-infix=*)
		DIFF_INFIX=${1#--diff-infix=}
		shift
		echo "Will diff against infix \"$DIFF_INFIX\""
		;;
	-*)
		die "Unrecognized option \"$1\""
		;;
	esac
done


sort-stat() {
	# Perl:
	# * Use slurp mode.
	# * Read in entire data.
	# * Split into records at line beginnings that contain a file name,
	#   using a zero-width look-ahead so the match won't be removed.
	# * Sort records by string comparison and output the results.
	#   As they should all begin with "  File:", this should effectively
	#   sort by file name.
	# * Let's hope that this won't explode on big (several hundreds of MiB?
	#   or even larger?) input data.
	perl -e 'undef $/; my $data = <>; my @records = split(/^(?=  File:)/m, $data); print sort { $a cmp $b } @records'
}


RET=0

for SUBVOL
do
	[ -d "$SUBVOL" ] || die "Not a directory: $SUBVOL"

	[ "$(stat --format="%i" "$SUBVOL")" -eq 256 ] || die "Not a btrfs subvolume: $SUBVOL"


	export SUBVOL_STAT_LOG="${SUBVOL}${INFIX}.stat.log"
	export SUBVOL_CHECKSUMS_FILE="${SUBVOL}${INFIX}.sha256"

	[ -e "$SUBVOL_STAT_LOG" ] && die "Stat log file for btrfs subvolume \"$SUBVOL\" already exists: $SUBVOL_STAT_LOG"
	[ -e "$SUBVOL_CHECKSUMS_FILE" ] && die "Checksums file for btrfs subvolume \"$SUBVOL\" already exists: $SUBVOL_CHECKSUMS_FILE"

	exec {SUBVOL_STAT_LOG_FD}>>"$SUBVOL_STAT_LOG" || die "Couldn't open stat log file for btrfs subvolume \"$SUBVOL\": $SUBVOL_STAT_LOG"
	export SUBVOL_STAT_LOG_FD

	exec {SUBVOL_CHECKSUMS_FILE_FD}>>"$SUBVOL_CHECKSUMS_FILE" || die "Couldn't open checksums file for btrfs subvolume \"$SUBVOL\": $SUBVOL_CHECKSUMS_FILE"
	export SUBVOL_CHECKSUMS_FILE_FD 


	echo
	echo "Processing btrfs subvolume $SUBVOL ..."

	( cd "$SUBVOL" && find \
		! -path . -inum 256 -printf "Pruning child subvolume %p\n" -prune , \
		-type f -exec bash -c "sha256sum --binary -- \"\$@\" >&\"\$SUBVOL_CHECKSUMS_FILE_FD\"" checksums "{}" + , \
		-exec bash -c "stat -- \"\$@\" >&\"\$SUBVOL_STAT_LOG_FD\"" stat-log "{}" +
	) || die "Subshell with cd and find exited unsuccessfully (with exit code $?)"


	if [ -n "$DIFF_INFIX" ]
	then
		echo "Diffing meta-data of subvol \"$SUBVOL\" from infix \"$DIFF_INFIX\" to infix \"$INFIX\"..."

		SUBVOL_STAT_LOG_PREV="${SUBVOL}${DIFF_INFIX}.stat.log"
		SUBVOL_CHECKSUMS_FILE_PREV="${SUBVOL}${DIFF_INFIX}.sha256"

		echo "Diffing checksums:"
		if ! diff <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE_PREV") <(sort -k2 <"$SUBVOL_CHECKSUMS_FILE")
		then
			warn "Warning: Checksum differences found for subvol \"$SUBVOL\", from infix \"$DIFF_INFIX\" to infix \"$INFIX\""
			[ "$RET" -lt 1 ] && RET=1
		fi

		echo "Diffing stat results:"
		if ! diff -U8 <(sort-stat <"$SUBVOL_STAT_LOG_PREV") <(sort-stat <"$SUBVOL_STAT_LOG")
		then
			warn "Warning: stat differences found for subvol \"$SUBVOL\", from infix \"$DIFF_INFIX\" to infix \"$INFIX\""
			[ "$RET" -lt 1 ] && RET=1
		fi
	fi


	exec {SUBVOL_CHECKSUMS_FILE_FD}>&- || die "Couldn't close checksums file for btrfs subvolume \"$SUBVOL\": $SUBVOL_CHECKSUMS_FILE"
	unset SUBVOL_CHECKSUMS_FILE_FD SUBVOL_CHECKSUMS_FILE

	exec {SUBVOL_STAT_LOG_FD}>&- || die "Couldn't close stat log file for btrfs subvolume \"$SUBVOL\": $SUBVOL_STAT_LOG"
	unset SUBVOL_STAT_LOG_FD SUBVOL_STAT_LOG
done

if [ "$RET" -ne 0 ]
then
	warn "Warning: Exiting unsuccessfully"
fi

exit "$RET"
