#!/bin/bash

set -o pipefail

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"

	# Close SSH stdin pipe fd, to allow the connection to die.
	# (But, in fact, doesn't seem to help. ..?)
	if [ -n "$CST_SSH_STDIN" ]
	then
		exec {CST_SSH_STDIN}>&- || warn "Failed to close SSH standard input"
	fi

	exit 1
}

CST_SHELL_CLEANUP_RAN=
CST_TMP_DIR=
CST_SSH_PID=
shell_cleanup() {
	[ -n "$CST_SHELL_CLEANUP_RAN" ] && return 0
	CST_SHELL_CLEANUP_RAN=1

	SIG=
	[ "$#" -ge 1 ] && { SIG="$1"; shift; }
	FAIL=0
	if [ -n "$CST_TMP_DIR" ] && [ -d "$CST_TMP_DIR" ]
	then
		rm -r "$CST_TMP_DIR" || FAIL=1
		CST_TMP_DIR=
	fi

	if [ -n "$CST_SSH_PID" ]
	then
		kill "$CST_SSH_PID" || FAIL=1
		CST_SSH_PID=
	fi

	# Re-raise signal.
	case "$SIG" in
	"")
		;;
	EXIT)
		trap - "$SIG"
		exit "$FAIL"
		;;
	*)
		trap - "$SIG"
		kill -"$SIG" "$$"
		;;
	esac
}
trap 'shell_cleanup TERM' TERM
trap 'shell_cleanup INT'  INT
trap 'shell_cleanup HUP'  HUP
trap 'shell_cleanup EXIT' EXIT

CST_DIR="$(dirname "$0")"
. "$CST_DIR/liblog.sh" || die "Failed to source shell library liblog.sh"
. "$CST_DIR/libbtrfs.sh" || die "Failed to source shell library libbtrfs.sh"


USAGE="Usage: $0 OUTPUT_PREFIX [LAST_SNAPSHOT_NUMBER]"

MODE="sendfiles"
SKIP_CLEANUPS="timeline"

while [ "$#" -ge 1 ] && [ "${1:0:1}" = "-" ]
do
	case "$1" in
	--help|--usage)
		shift
		echo "$USAGE"
		exit 0
		;;
	--files)
		MODE="sendfiles"
		shift
		SKIP_CLEANUPS="timeline"
		;;
	--receive)
		MODE="sendreceive"
		shift
		SKIP_CLEANUPS=
		;;
	--remote=*)
		MODE="remote"
		REMOTE_HOST="${1#--remote=}"
		shift
		SKIP_CLEANUPS=
		;;
	*)
		die "Invalid option \"$1\""
		;;
	esac
done

[ "$#" -ge 1 ] || die "$USAGE"

OUTPUT_PREFIX="$1"; shift
LAST_SNAPSHOT_NUMBER_ARG=

[ "$#" -ge 1 ] && { LAST_SNAPSHOT_NUMBER_ARG="$1"; shift; }

[ "$#" -eq 0 ] || die "Too many arguments -- $USAGE"


LAST_SNAPSHOT_NUMBER_ARG_REACHED=0
LAST_SNAPSHOT_NUMBER=

main() {
if [ "$MODE" = "remote" ]
then
	exec {CST_SSH_STDOUT}<&0 || die "Couldn't duplicate main() stdin for continued reading from SSH"

	CST_THIS_SIDE="CVNSNAPPER_REPLICATE_SENDER"
	CST_EXPECTED_OTHER_SIDE="CVNSNAPPER_REPLICATE_RECEIVER"

	CST_THIS_PROTO_MIN=0
	CST_THIS_PROTO=2
	CST_STATE_OTHER_PROTO=


	# Read pre-initial (protocol version) message.
	read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read pre-initial message from remote host"

	[ "$CST_OTHER_WHO" = "$CST_EXPECTED_OTHER_SIDE" ] || die "Invalid other side message: By \"$CST_OTHER_WHO\""
	[ "$CST_OTHER_WHAT" = "proto" ] || die "Unexpected initial message from other side: \"$CST_OTHER_WHAT\""

	read CST_OTHER_PROTO CST_OTHER_REST <<<"$CST_OTHER_REST"
	[ -n "$CST_OTHER_PROTO" ] || die "Invalid other side message: \"proto\" message missing protocol number..."
	[ -n "$CST_OTHER_REST" ] && die "Invalid other side message: \"proto\" message with trailing data..."
	# TODO: Validate as number, and only a number.

	if [ "$CST_OTHER_PROTO" = "$CST_THIS_PROTO" ]
	then
		msg_debug "Other side's protocol \"$CST_OTHER_PROTO\" matches our side \"$CST_THIS_PROTO\""
	elif [ "$CST_OTHER_PROTO" -lt "$CST_THIS_PROTO" ]
	then
		msg_debug "Other side's protocol \"$CST_OTHER_PROTO\" is less than our side \"$CST_THIS_PROTO\""
		[ "$CST_OTHER_PROTO" -ge "$CST_THIS_PROTO_MIN" ] || die "Other side's protocol \"$CST_OTHER_PROTO\" is less than our side's minimum \"$CST_THIS_PROTO_MIN\", aborting"
		CST_THIS_PROTO="$CST_OTHER_PROTO"
	else
		msg_debug "Other side's protocol \"$CST_OTHER_PROTO\" seemingly higher, trying to lower to our default protocol \"$CST_THIS_PROTO\"..."
		CST_OTHER_PROTO="$CST_THIS_PROTO"
	fi
	CST_STATE_OTHER_PROTO="$CST_OTHER_PROTO"

	echo "$CST_THIS_SIDE proto $CST_THIS_PROTO" >&"$CST_SSH_STDIN" || die "Couldn't send protocol message reply that we support \"proto\" (protocol number) \"$CST_THIS_PROTO\""


	# Read initial message.
	read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read initial message from remote host"

	[ "$CST_OTHER_WHO" = "$CST_EXPECTED_OTHER_SIDE" ] || die "Invalid other side message: By \"$CST_OTHER_WHO\""
	[ "$CST_OTHER_WHAT" = "have" ] || die "Unexpected initial message from other side: \"$CST_OTHER_WHAT\""

	if [ -z "$LAST_SNAPSHOT_NUMBER_ARG" ]
	then
		LAST_SNAPSHOT_NUMBER_ARG="$CST_OTHER_REST"
	else
		[ "$CST_OTHER_REST" -eq "$LAST_SNAPSHOT_NUMBER_ARG" ] || warn "Warning: Snapshot number the remote has, \"$CST_OTHER_REST\", and that we will be using, \"$LAST_SNAPSHOT_NUMBER_ARG\", don't match"
	fi

	echo "$CST_THIS_SIDE can $LAST_SNAPSHOT_NUMBER_ARG" >&"$CST_SSH_STDIN" || die "Couldn't send protocol message reply that we \"can\" snapshot number \"$LAST_SNAPSHOT_NUMBER_ARG\""


	read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read 2nd message from remote host"

	[ "$CST_OTHER_WHO" = "$CST_EXPECTED_OTHER_SIDE" ] || die "Invalid other side message: By \"$CST_OTHER_WHO\""
	[ "$CST_OTHER_WHAT" = "receivedUUID" ] || die "Unexpected 2nd message from other side: \"$CST_OTHER_WHAT\""

	read CST_OTHER_SNAPSHOT_NUMBER OUT_RECEIVED_UUID <<<"$CST_OTHER_REST"
	[ -n "$CST_OTHER_SNAPSHOT_NUMBER" ] || die "Incomplete 2nd message from other side: Received UUID snapshot number missing!"
	[ -n "$OUT_RECEIVED_UUID" ] || die "Incomplete 2nd message from other side: Received UUID missing!"
	[ "$CST_OTHER_SNAPSHOT_NUMBER" = "$LAST_SNAPSHOT_NUMBER_ARG" ] || die "2nd message received UUID snapshot number \"$CST_OTHER_SNAPSHOT_NUMBER\" to our last snapshot number argument \"$LAST_SNAPSHOT_NUMBER_ARG\" mismatch, aborting"

	# Sanity check. (Read further down.)
	CHECK_TEXT="connection between last remote snapshot and corresponding local input snapshot"
elif [ "$MODE" = "sendreceive" ]
then
	is_subvol "$OUTPUT_PREFIX" || die "In mode $MODE, output prefix must be a subvolume"

	OUTPUT_SNAPSHOTS="$OUTPUT_PREFIX/.snapshots"
	is_subvol "$OUTPUT_SNAPSHOTS" || die "Output prefix snapper .snapshots subvolume not a subvolume at \"$OUTPUT_SNAPSHOTS\""

	if [ -z "$LAST_SNAPSHOT_NUMBER_ARG" ]
	then
		LAST_SNAPSHOT_NUMBER_ARG=$(cd "$OUTPUT_SNAPSHOTS" && ls -1d [1-9]* | sort -n | tail -1)
	fi

	if [ -n "$LAST_SNAPSHOT_NUMBER_ARG" ]
	then
		# Sanity check.
		CHECK_TEXT="connection between last output prefix snapshot and corresponding input snapshot"

		OUT_SNAP="$OUTPUT_SNAPSHOTS/$LAST_SNAPSHOT_NUMBER_ARG/snapshot"
		is_subvol "$OUT_SNAP" || die "Failed to sanity-check $CHECK_TEXT: Last output prefix snapshot \"$OUT_SNAP\" is not a subvolume"
		OUT_RECEIVED_UUID="$(subvol_get_received_uuid "$OUT_SNAP")" || die "Failed to sanity-check $CHECK_TEXT: Failed to get received UUID of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
		[ "$OUT_RECEIVED_UUID" = "-" ] && die "Failed to sanity-check $CHECK_TEXT: Invalid received UUID \"$OUT_RECEIVED_UUID\" of last output prefix snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\""
	fi
fi

case "$MODE" in
remote|sendreceive)
	IN_SNAP="$LAST_SNAPSHOT_NUMBER_ARG/snapshot"
	is_subvol "$IN_SNAP" || die "Failed to sanity-check $CHECK_TEXT: Input snapshot \"$IN_SNAP\" is not a subvolume"
	IN_UUID="$(subvol_get_uuid "$IN_SNAP")" || die "Failed to sanity-check $CHECK_TEXT: Couldn't get input snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s UUID"

	if ! [ "$OUT_RECEIVED_UUID" = "$IN_UUID" ]
	then
		# Allow both sides having been received from the same
		# source subvolume somewhere else, too.

		IN_RECEIVED_UUID="$(subvol_get_received_uuid "$IN_SNAP")" || die "Failed to sanity-check $CHECK_TEXT: Couldn't get input snapshot \"$LAST_SNAPSHOT_NUMBER_ARG\"'s received UUID"
		[ "$OUT_RECEIVED_UUID" = "$IN_RECEIVED_UUID" ] || die "Failed to sanity-check $CHECK_TEXT: Receiving side's received UUID \"$OUT_RECEIVED_UUID\" neither matches sending side's UUID \"$IN_UUID\" nor received UUID \"$IN_RECEIVED_UUID\""
	fi
	;;
esac

CST_SENT_SNAPNUMS=
while read SNAPSHOT_NUMBER
do
	# Skip snapshots silently until last-arg, if last-arg was given.
	if [ -n "$LAST_SNAPSHOT_NUMBER_ARG" ] && [ "$LAST_SNAPSHOT_NUMBER_ARG_REACHED" -eq 0 ]
	then
		[ "$SNAPSHOT_NUMBER" -lt "$LAST_SNAPSHOT_NUMBER_ARG" ] && continue

		[ "$SNAPSHOT_NUMBER" -eq "$LAST_SNAPSHOT_NUMBER_ARG" ] || die "Last snapshot number \"$LAST_SNAPSHOT_NUMBER_ARG\" missing"

		LAST_SNAPSHOT_NUMBER_ARG_REACHED=1
		LAST_SNAPSHOT_NUMBER="$SNAPSHOT_NUMBER"

		# Sanity-check before trying to use this as parent later.
		is_subvol "$SNAPSHOT_NUMBER/snapshot" || die "Snapshot under last snapshot number \"$LAST_SNAPSHOT_NUMBER_ARG\" missing"

		continue
	fi


	#
	# Consider snapshot number verbosely, and possibly skip.
	#

	is_info && echo -n "snapper snapshot number $SNAPSHOT_NUMBER: "

	SNAPSHOT_INFO="$SNAPSHOT_NUMBER/info.xml"
	[ -f "$SNAPSHOT_INFO" ] || { is_info && echo "(error)"; die "Missing info.xml at snapper snapshot number $SNAPSHOT_NUMBER"; }

	SNAPSHOT_NUM=$(sed -n -e 's#^.*<num>\([^<]*\)</num>.*#\1#p' <"$SNAPSHOT_INFO") || { is_info && echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER num: sed failed"; }
	[ "$SNAPSHOT_NUMBER" = "$SNAPSHOT_NUM" ] || { is_info && echo "(error)"; die "Meta-data \"num\" does not match at snapper snapshot number $SNAPSHOT_NUMBER "; }

	SNAPSHOT_DATE=$(sed -n -e 's#^.*<date>\([^<]*\)</date>.*#\1#p' <"$SNAPSHOT_INFO") || { is_info && echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER date: sed failed"; }
	SNAPSHOT_TYPE=$(sed -n -e 's#^.*<type>\([^<]*\)</type>.*#\1#p' <"$SNAPSHOT_INFO") || { is_info && echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER type: sed failed"; }
	SNAPSHOT_UID=$(sed -n -e 's#^.*<uid>\([^<]*\)</uid>.*#\1#p' <"$SNAPSHOT_INFO") || { is_info && echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER uid: sed failed"; }
	SNAPSHOT_DESCRIPTION=$(sed -n -e 's#^.*<description>\([^<]*\)</description>.*#\1#p' <"$SNAPSHOT_INFO") || { is_info && echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER description: sed failed"; }

	SNAPSHOT_CLEANUP=$(sed -n -e 's#^.*<cleanup>\([^<]*\)</cleanup>.*#\1#p' <"$SNAPSHOT_INFO") || { is_info && echo "(error)"; die "While extracting snapper snapshot number $SNAPSHOT_NUMBER cleanup policy: sed failed"; }
	SKIP=0
	for SKIP_CLEANUP in $SKIP_CLEANUPS
	do
		if [ "$SNAPSHOT_CLEANUP" = "$SKIP_CLEANUP" ]
		then
			if is_info
			then echo "(Skipping due to cleanup policy \"$SNAPSHOT_CLEANUP\": Date $SNAPSHOT_DATE type $SNAPSHOT_TYPE${SNAPSHOT_UID:+ uid $SNAPSHOT_UID}${SNAPSHOT_CLEANUP:+ cleanup $SNAPSHOT_CLEANUP}: \"$SNAPSHOT_DESCRIPTION\")"
			else echo "(Skipping snapshot number $SNAPSHOT_NUMBER: cleanup $SNAPSHOT_CLEANUP)"
			fi
			SKIP=1
			break
		fi
	done
	[ "$SKIP" -eq 0 ] || continue

	is_info && echo "Date $SNAPSHOT_DATE type $SNAPSHOT_TYPE${SNAPSHOT_UID:+ uid $SNAPSHOT_UID}${SNAPSHOT_CLEANUP:+ cleanup $SNAPSHOT_CLEANUP}: \"$SNAPSHOT_DESCRIPTION\""


	#
	# Do the btrfs send operation.
	#

	CST_SENT_SNAPNUMS="$CST_SENT_SNAPNUMS $SNAPSHOT_NUMBER"

	INPUT_SNAPSHOT="$SNAPSHOT_NUMBER/snapshot"
	is_subvol "$INPUT_SNAPSHOT" || die "No input snapshot under snapshot number $SNAPSHOT_NUMBER"

	if [ -z "$LAST_SNAPSHOT_NUMBER" ]
	then
		echo -n "Full send of $SNAPSHOT_NUMBER: "

		case "$MODE" in
		sendfiles)
			OUTPUT_FILE="${OUTPUT_PREFIX}-${SNAPSHOT_NUMBER}-full.btrfs_send"
			[ -e "$OUTPUT_FILE" ] && { echo "(error)"; die "Output file \"$OUTPUT_FILE\" already exists"; }

			btrfs send -f "$OUTPUT_FILE" "$INPUT_SNAPSHOT" || { echo "(error)"; die "While doing full send of snapshot number $SNAPSHOT_NUMBER: btrfs send failed"; }
			;;
		sendreceive)
			OUTPUT_SNAPSHOT_DIR="$OUTPUT_SNAPSHOTS/$SNAPSHOT_NUMBER"
			mkdir "$OUTPUT_SNAPSHOT_DIR" || { echo "(error)"; die "Couldn't create output snapper .snapshots sub-directory \"$OUTPUT_SNAPSHOT_DIR\""; }
			btrfs send "$INPUT_SNAPSHOT" | btrfs receive "$OUTPUT_SNAPSHOT_DIR" || { CODE="$?"; echo "(error)"; die "While doing full send-receive of snapshot number $SNAPSHOT_NUMBER: btrfs send|receive pipeline failed (with code $CODE)"; }
			# After successful receive, transfer snapper meta-data,
			# as well, to give a snapper for the destination
			# the chance to list and handle the snapshot.
			# (Note that line has already been ended by btrfs output.)
			cp -a "$SNAPSHOT_INFO" "$OUTPUT_SNAPSHOT_DIR/" || die "Copying snapshot info \"$SNAPSHOT_INFO\" to output snapshot directory \"$OUTPUT_SNAPSHOT_DIR\" failed (with code $?)"
			;;
		remote)
			echo "(error)"
			die "Full send (of snapshot \"$SNAPSHOT_NUMBER\") not implemented, yet"
			;;
		*)
			echo "(error)"
			die "Unsupported mode-of-operation \"$MODE\""
			;;
		esac
	else
		INPUT_PARENT_SNAPSHOT="$LAST_SNAPSHOT_NUMBER/snapshot"
		is_subvol "$INPUT_PARENT_SNAPSHOT" || die "No parent snapshot under last snapshot number $LAST_SNAPSHOT_NUMBER"

		echo -n "Incremental send from $LAST_SNAPSHOT_NUMBER to $SNAPSHOT_NUMBER: "

		case "$MODE" in
		sendfiles)
			OUTPUT_FILE="${OUTPUT_PREFIX}-${SNAPSHOT_NUMBER}.btrfs_send"
			[ -e "$OUTPUT_FILE" ] && { echo "(error)"; die "Output file \"$OUTPUT_FILE\" already exists"; }

			btrfs send -f "$OUTPUT_FILE" -p "$INPUT_PARENT_SNAPSHOT" "$INPUT_SNAPSHOT" || { echo "(error)"; die "While doing incremental send of snapshot number $SNAPSHOT_NUMBER with parent $LAST_SNAPSHOT_NUMBER: btrfs send failed"; }
			;;
		sendreceive)
			OUTPUT_SNAPSHOT_DIR="$OUTPUT_SNAPSHOTS/$SNAPSHOT_NUMBER"
			mkdir "$OUTPUT_SNAPSHOT_DIR" || { echo "(error)"; die "Couldn't create output snapper .snapshots sub-directory \"$OUTPUT_SNAPSHOT_DIR\""; }
			btrfs send -p "$INPUT_PARENT_SNAPSHOT" "$INPUT_SNAPSHOT" | btrfs receive "$OUTPUT_SNAPSHOT_DIR" || { CODE="$?"; echo "(error)"; die "While doing incremental send-receive of snapshot number $SNAPSHOT_NUMBER with parent $LAST_SNAPSHOT_NUMBER: btrfs send|receive pipeline failed (with code $CODE)"; }
			cp -a "$SNAPSHOT_INFO" "$OUTPUT_SNAPSHOT_DIR/" || die "Copying snapshot info \"$SNAPSHOT_INFO\" to output snapshot directory \"$OUTPUT_SNAPSHOT_DIR\" failed (with code $?)"
			;;
		remote)
			echo "$CST_THIS_SIDE receive $SNAPSHOT_NUMBER" >&"$CST_SSH_STDIN" || die "Failed to send protocol message for the remote host to receive snapshot number \"$SNAPSHOT_NUMBER\""
			btrfs send -p "$INPUT_PARENT_SNAPSHOT" "$INPUT_SNAPSHOT" >&"$CST_SSH_STDIN" || die "Sending \"btrfs send\" stream to remote host failed"

			# Since proto 2, also transfer the info.xml, in-band.
			if [ "$CST_THIS_PROTO" -ge 2 ]
			then
				msg_debug "proto >= 2: Sending info.xml ..."
				INPUT_INFO="$SNAPSHOT_NUMBER/info.xml"
				( base64 --wrap=0 "$INPUT_INFO"; RET="$?"; echo || exit; exit "$RET" ) >&"$CST_SSH_STDIN" || die "Sending \"$INPUT_INFO\" data to remote host failed"
				date -Ins --reference="$INPUT_INFO" >&"$CST_SSH_STDIN" || die "Sending \"$INPUT_INFO\" timestamp to remote host failed"
			fi

			read CST_OTHER_WHO CST_OTHER_WHAT CST_OTHER_REST <&"$CST_SSH_STDOUT" || die "Couldn't read send stream response message from remote host"
			[ "$CST_OTHER_WHO" = "$CST_EXPECTED_OTHER_SIDE" ] || die "Invalid other side message: By \"$CST_OTHER_WHO\""
			[ "$CST_OTHER_WHAT" = "receivedUUID" ] || die "Unexpected send stream response message from other side: \"$CST_OTHER_WHAT\""
			OUT_RECEIVED_UUID="$CST_OTHER_REST"
			[ -n "$OUT_RECEIVED_UUID" ] || die "Incomplete send stream response message from other side: Received UUID missing!"
			# TODO: Check received UUID against UUID of subvol we wanted to send?
			;;
		*)
			echo "(error)"
			die "Unsupported mode-of-operation \"$MODE\""
			;;
		esac
	fi
	LAST_SNAPSHOT_NUMBER="$SNAPSHOT_NUMBER"
done < <(ls -1d [1-9]* | sort -n)

echo "Finished main operation. Sent:${CST_SENT_SNAPNUMS:- (none)}"

if [ "$MODE" = "remote" ]
then
	echo "$CST_THIS_SIDE end" >&"$CST_SSH_STDIN" || die "Sending \"end\" message failed"
	warn "Waiting for remote side to finish..."
	read CST_OTHER_LINE <&"$CST_SSH_STDOUT" && die "Error! Remote side still had more to say! \"$CST_OTHER_LINE\""
fi

# Post-operation.
if [ "$MODE" = "sendreceive" ] && [ -n "$CST_SENT_SNAPNUMS" ]
then
	# Update the active subvol with the last sent snapshot,
	# hanging the .snapshots subvol into there.
	"$CST_DIR/replace-active" "$OUTPUT_PREFIX" "$LAST_SNAPSHOT_NUMBER" || die "Post-operation: Failed to update output active subvolume at \"$OUTPUT_PREFIX\""
fi
}  # End of main(), needed for piping SSH.

if [ "$MODE" = "remote" ]
then
	CST_TMP_DIR="$(mktemp -d)" || die "Couldn't create temporary directory for named pipes for SSH redirection"
	[ -n "$CST_TMP_DIR" ] || die "Couldn't create temporary directory for named pipes for SSH redirection: Result was empty"
	[ -d "$CST_TMP_DIR" ] || die "Couldn't create temporary directory for named pipes for SSH redirection: Is not a directory: \"$CST_TMP_DIR\""
	mkfifo --mode="700" "$CST_TMP_DIR/ssh_stdin"  || die "Couldn't create named pipe for SSH input redirection"
	#mkfifo --mode="700" "$CST_TMP_DIR/ssh_stdout" || die "Couldn't create named pipe for SSH output redirection"

	# Spawn SSH to other host.
	exec {CST_SSH_STDIN}<>"$CST_TMP_DIR/ssh_stdin" || die "SSH input redirection failed"
	[ -n "$CST_SSH_STDIN"  ] || die "Couldn't get SSH stdin fd redirection: Result is empty"
	#exec {CST_SSH_STDOUT}<>"$CST_TMP_DIR/ssh_stdout" || die "SSH output redirection failed"
	#[ -n "$CST_SSH_STDOUT" ] || die "Couldn't get SSH stdout fd redirection: Result is empty"
	${CVNSNAPPER_TOOLBOX_SSH:-ssh} \
		"$REMOTE_HOST" \
		${CVNSNAPPER_TOOLBOX_REMOTE_COMMAND:-cvnsnapper replicate-receive} "$OUTPUT_PREFIX" \
		<"$CST_TMP_DIR/ssh_stdin" \
		| main || die "\"ssh | main\" pipeline failed"
else
	main
fi

exit 0
