#!/bin/bash

set -o pipefail

warn() {
	echo "${0##*/}: $*" >&2
}

die() {
	warn "Fatal: $*"
	exit 1
}


CST_DIR="$(dirname "$0")"
. "$CST_DIR/liblog.sh" || die "Failed to source shell library liblog.sh"
. "$CST_DIR/libbtrfs.sh" || die "Failed to source shell library libbtrfs.sh"
. "$CST_DIR/libsnapper.sh" || die "Failed to source shell library libsnapper.sh"


CST_USAGE="Usage: $0 OUTPUT_SUBVOL_CANDIDATES"

CST_THIS_SIDE="CVNSNAPPER_REPLICATE_RECEIVER"
CST_THIS_PROTO_MIN=0
CST_THIS_PROTO=3


# Parse (supposedly) forced-command command-line.

while [ "$#" -ge 1 ] && [ "${1:0:1}" = "-" ]
do
	CST_OPT="$1"
	case "$CST_OPT" in
	--usage|--help)
		echo "$CST_USAGE"
		exit 0
		;;
	*)
		die "Unrecognized command-line option \"$CST_OPT\", aborting"
		;;
	esac
done

[ "$#" -ge 1 ] || die "$CST_USAGE"

# "$@" should now contain a list of allowed subvolumes; used further below.


# Parse original command command-line.

[ -n "$SSH_ORIGINAL_COMMAND" ] || die "Missing original command in environment"

read CST_REMOTE_CMD CST_REMOTE_REST <<<"$SSH_ORIGINAL_COMMAND"
[ -n "$CST_REMOTE_CMD" ] || die "Missing original command name"
CST_REMOTE_CMD_BASENAME="${CST_REMOTE_CMD##*/}"
CST_THIS_CMD_BASENAME="${0##*/}"
[ "$CST_REMOTE_CMD_BASENAME" = "$CST_THIS_CMD_BASENAME" ] || die "This forced-command based invocation of $CST_THIS_CMD_BASENAME does not seem to be what the other side is requesting: \"$CST_REMOTE_CMD_BASENAME\""
[ -n "$CST_REMOTE_REST" ] || die "Original command is missing further arguments; should be specifying the path to an allowed snapper-style subvolume"

CST_REMOTE_REQSUBVOL=
while [ -n "$CST_REMOTE_REST" ] && read CST_REMOTE_ARG CST_REMOTE_REST <<<"$CST_REMOTE_REST"
do
	case "$CST_REMOTE_ARG" in
	-*)
		die "Unrecognized command-line option in original command: \"$CST_REMOTE_ARG\""
		;;
	*)
		[ -n "$CST_REMOTE_REQSUBVOL" ] && die "Original command tries to specify requested subvolume twice: \"$CST_REMOTE_REQSUBVOL\" and \"$CST_REMOTE_ARG\". Aborting"
		CST_REMOTE_REQSUBVOL="$CST_REMOTE_ARG"
		;;
	esac
done


# Now, check the remote-requested subvolume against forced-command allowed ones.

CST_OUTPUT_SUBVOL=
for CST_ALLOWED_SUBVOL
do
	if [ "$CST_ALLOWED_SUBVOL" = "$CST_REMOTE_REQSUBVOL" ]
	then
		CST_OUTPUT_SUBVOL="$CST_REMOTE_REQSUBVOL"
		break
	fi
done

[ -n "$CST_OUTPUT_SUBVOL" ] || die "Remote-requested subvolume \"$CST_REMOTE_REQSUBVOL\" not in the list of allowed subvolumes!"


is_subvol "$CST_OUTPUT_SUBVOL" || die "Output subvolume is not a subvolume: \"$CST_OUTPUT_SUBVOL\""

[ "$(btrfs property get "$CST_OUTPUT_SUBVOL" ro)" = "ro=true" ] || die "Output subvolume is not read-only: \"$CST_OUTPUT_SUBVOL\""


CST_OUTPUT_SNAPSHOTS="$CST_OUTPUT_SUBVOL/.snapshots"

is_subvol "$CST_OUTPUT_SNAPSHOTS" || die "Output snapper .snapshots subvolume is not a subvolume: \"$CST_OUTPUT_SNAPSHOTS\""

[ "$(btrfs property get "$CST_OUTPUT_SNAPSHOTS" ro)" = "ro=false" ] || die "Output snapper .snapshots subvolume *is* read-only though it shouldn't: \"$CST_OUTPUT_SNAPSHOTS\""


CST_SNAPSHOT_NUMBER="$(cd "$CST_OUTPUT_SNAPSHOTS" && ls -1d [1-9]* | sort -n | tail -1)" || die "Can't determine initial last snapshot number: Pipe failed"
[ -n "$CST_SNAPSHOT_NUMBER" ] || die "Can't determine initial last snapshot number: Result was empty"
is_number "$CST_SNAPSHOT_NUMBER" || die "Can't determine initial last snapshot number: Result does not validate as number"


protomsg_receivedUUID() {
	[ -n "$CST_SNAPSHOT_NUMBER" ] || die "Can't send protocol message \"receivedUUID\" as the current snapshot number is not set"

	CST_SNAP="$CST_OUTPUT_SNAPSHOTS/$CST_SNAPSHOT_NUMBER/snapshot"
	is_subvol "$CST_SNAP" || die "Snapshot \"$CST_SNAP\" is not a subvolume"
	CST_RECEIVED_UUID="$(subvol_get_received_uuid "$CST_SNAP")" || die "Couldn't retrieve received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\""
	[ "$CST_RECEIVED_UUID" = "-" ] && die "Received UUID for snapshot \"$CST_SNAPSHOT_NUMBER\" invalid: \"$CST_RECEIVED_UUID\""

	echo "$CST_THIS_SIDE receivedUUID $CST_SNAPSHOT_NUMBER $CST_RECEIVED_UUID"
}


# Get the conversation going...
echo "$CST_THIS_SIDE proto $CST_THIS_PROTO"
echo "$CST_THIS_SIDE have $CST_SNAPSHOT_NUMBER"

CST_EXPECTED_OTHER_SIDE="CVNSNAPPER_REPLICATE_SENDER"
CST_STATE_OTHER_PROTO=
CST_STATE_OTHER_MSGNUM=0

CST_RECEIVED_SNAPNUMS=

CST_GOT_END=
while read CST_OTHER_SIDE CST_OTHER_WHAT CST_OTHER_REST
do
	[ "$CST_OTHER_SIDE" = "$CST_EXPECTED_OTHER_SIDE" ] || die "Invalid other side message: By \"$CST_OTHER_SIDE\" (expected \"$CST_EXPECTED_OTHER_SIDE\")"
	: $((CST_STATE_OTHER_MSGNUM++))

	CST_BREAK=
	case "$CST_OTHER_WHAT" in
	proto)
		read CST_OTHER_PROTO CST_OTHER_REST <<<"$CST_OTHER_REST"
		[ -n "$CST_OTHER_PROTO" ] || die "Invalid other side message: \"proto\" message missing protocol number..."
		[ -n "$CST_OTHER_REST" ] && die "Invalid other side message: \"proto\" message with trailing data..."
		is_number "$CST_OTHER_PROTO" || die "Invalid other side message: \"proto\" message protocol number fails validation as number!"

		[ "$CST_STATE_OTHER_MSGNUM" -eq 1 ] || die "Other side protocol message must be first message!"
		[ -z "$CST_STATE_OTHER_PROTO" ] || die "Other side protocol has already been set! (to \"$CST_STATE_OTHER_PROTO\")"
		if [ "$CST_OTHER_PROTO" = "$CST_THIS_PROTO" ]
		then
			msg_debug "Other side's protocol \"$CST_OTHER_PROTO\" matches our side \"$CST_THIS_PROTO\""
		elif [ "$CST_OTHER_PROTO" -lt "$CST_THIS_PROTO" ]
		then
			msg_debug "Other side's protocol \"$CST_OTHER_PROTO\" is less than our side \"$CST_THIS_PROTO\""
			[ "$CST_OTHER_PROTO" -ge "$CST_THIS_PROTO_MIN" ] || die "Other side's protocol \"$CST_OTHER_PROTO\" is less than our side's minimum \"$CST_THIS_PROTO_MIN\", aborting"
		else
			die "Other side's protocol \"$CST_OTHER_PROTO\" not supported"
		fi
		CST_STATE_OTHER_PROTO="$CST_OTHER_PROTO"
		;;
	end)
		[ -z "$CST_OTHER_REST" ] || die "Invalid other side message: \"end\" message with trailing data..."
		CST_GOT_END=1
		CST_BREAK=1
		;;
	verbose)
		# (Accept always, while the send side will try to only send it with protocol >= 3 ...)
		read CST_OTHER_VERBOSE CST_OTHER_REST <<<"$CST_OTHER_REST"
		[ -n "$CST_OTHER_VERBOSE" ] || die "Invalid other side message: \"$CST_OTHER_WHAT\" message missing verbose level"
		[ -n "$CST_OTHER_REST" ] && die "Invalid other side message: \"$CST_OTHER_WHAT\" message with trailing data"
		is_number "$CST_OTHER_VERBOSE" || die "Invalid other side message: \"$CST_OTHER_WHAT\" message verbose level fails to validate as number"
		export CVNSNAPPER_TOOLBOX_VERBOSE="$CST_OTHER_VERBOSE"
		msg_debug "Verbose level reached $CVNSNAPPER_TOOLBOX_VERBOSE"
		;;
	can)
		read CST_REQUESTED_SNAPSHOT_NUMBER CST_OTHER_REST <<<"$CST_OTHER_REST"
		[ -n "$CST_REQUESTED_SNAPSHOT_NUMBER" ] || die "Invalid other side message: \"can\" message is missing snapshot number"
		[ -n "$CST_OTHER_REST" ] && die "Invalid other side message: \"can\" message with trailing data..."
		is_number "$CST_REQUESTED_SNAPSHOT_NUMBER" || die "Invalid other side message: \"can\" message snapshot number fails validation as number!"

		if [ "$CST_REQUESTED_SNAPSHOT_NUMBER" = "$CST_SNAPSHOT_NUMBER" ]
		then
			msg_debug "Other side \"can\" same snapshot as we were at, $CST_SNAPSHOT_NUMBER"
		elif [ "$CST_REQUESTED_SNAPSHOT_NUMBER" -lt "$CST_SNAPSHOT_NUMBER" ]
		then
			msg_debug "Other side \"can\" only snapshot $CST_REQUESTED_SNAPSHOT_NUMBER, while we're at $CST_SNAPSHOT_NUMBER. Backing off to more older snapshots..."
			CST_CONTEXT_TEXT="Backing off from our snapshot $CST_SNAPSHOT_NUMBER to reach other side's \"can\" $CST_REQUESTED_SNAPSHOT_NUMBER"
			CST_FOUND=
			CST_SEARCH_SNAPNUM="$CST_SNAPSHOT_NUMBER"
			while [ "$CST_SEARCH_SNAPNUM" -gt "$CST_REQUESTED_SNAPSHOT_NUMBER" ]
			do
				: $((CST_SEARCH_SNAPNUM--))

				CST_SEARCH_SNAPSHOT_DIR="$CST_OUTPUT_SNAPSHOTS/$CST_SEARCH_SNAPNUM"
				[ -d "$CST_SEARCH_SNAPSHOT_DIR" ] || continue  # Not present at all.

				if [ "$CST_SEARCH_SNAPNUM" -eq "$CST_REQUESTED_SNAPSHOT_NUMBER" ]
				then
					is_subvol "$CST_SEARCH_SNAPSHOT_DIR/snapshot" || break

					CST_FOUND=1
					break
				fi

				SNAPSHOT_INFO="$CST_SEARCH_SNAPSHOT_DIR/info.xml"
				[ -f "$SNAPSHOT_INFO" ] || die "$CST_CONTEXT_TEXT failed: snapper snapshot info.xml \"$SNAPSHOT_INFO\" missing"
				parse_snapper_info || die "$CST_CONTEXT_TEXT failed: Failed to parse snapper snapshot info.xml: \"$SNAPSHOT_INFO\""

				[ "$SNAPSHOT_NUM" = "$CST_SEARCH_SNAPNUM" ] || die "$CST_CONTEXT_TEXT failed: snapper snapshot number $CST_SEARCH_SNAPNUM gave number \"$SNAPSHOT_NUM\" in info.xml: \"$SNAPSHOT_INFO\""

				case "$SNAPSHOT_CLEANUP" in
				timeline|number)
					# Allow skipping this snapshot.
					continue
					;;
				esac
				die "$CST_CONTEXT_TEXT failed: Unsuitable (unskippable) snapshot number $CST_SEARCH_SNAPNUM found, aborting"
			done
			[ -n "$CST_FOUND" ] || die "$CST_CONTEXT_TEXT failed: Requested snapshot not found"
			msg_info "Backing off from our snapshot $CST_SNAPSHOT_NUMBER to $CST_SEARCH_SNAPNUM after other side's \"can\" $CST_REQUESTED_SNAPSHOT_NUMBER"
			CST_SNAPSHOT_NUMBER="$CST_SEARCH_SNAPNUM"
		else
			die "Other side \"can\" only snapshot $CST_REQUESTED_SNAPSHOT_NUMBER, while we're still at $CST_SNAPSHOT_NUMBER; impossible(?), aborting"
		fi
		protomsg_receivedUUID || die "Error in sending our next protocol message \"receivedUUID\" (after \"can\"), aborting"
		;;
	receive)
		read CST_RECEIVE_SNAPSHOT_NUMBER CST_OTHER_REST <<<"$CST_OTHER_REST"
		[ -n "$CST_RECEIVE_SNAPSHOT_NUMBER" ] || die "Invalid other side message: \"receive\" message is missing snapshot number"
		[ -n "$CST_OTHER_REST" ] && die "Invalid other side message: \"receive\" message with trailing data..."
		is_number "$CST_RECEIVE_SNAPSHOT_NUMBER" || die "Invalid other side message: \"receive\" message snapshot number fails validation as number!"

		[ "$CST_RECEIVE_SNAPSHOT_NUMBER" -gt "$CST_SNAPSHOT_NUMBER" ] || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\" is forbidden as it is not later than \"$CST_SNAPSHOT_NUMBER\""


		# Determine & prepare receiving directory (in snapper .snapshots subvol structure)...
		CST_OUTPUT_SNAPSHOT_DIR="$CST_OUTPUT_SNAPSHOTS/$CST_RECEIVE_SNAPSHOT_NUMBER"
		[ -e "$CST_OUTPUT_SNAPSHOT_DIR" ] && die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Snapshot directory already exists"
		mkdir "$CST_OUTPUT_SNAPSHOT_DIR" || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Couldn't create snapshot directory"

		# Do the actual receive...
		btrfs receive -e "$CST_OUTPUT_SNAPSHOT_DIR/" >&2 || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Failed in \"btrfs receive\""
		# ^ The -e lets btrfs receive end at an end-marker, instead of only on EOF (which we don't have).
		#   The >&2 is an attempt to get the "At ..." message to the error stream, where it won't gobble up our protocol messages.
		CST_RECEIVED_SNAPNUMS="$CST_RECEIVED_SNAPNUMS $CST_RECEIVE_SNAPSHOT_NUMBER"

		# Since protocol 2, we'll also receive the snapper info.xml, in-band.
		if [ "$CST_STATE_OTHER_PROTO" -ge 2 ]
		then
			msg_debug "proto >= 2: Receiving info.xml ..."
			CST_OUTPUT_INFO="$CST_OUTPUT_SNAPSHOT_DIR/info.xml"
			( read THE_BASE64 || exit; umask 077 || exit; base64 --decode >"$CST_OUTPUT_INFO" <<<"$THE_BASE64" ) || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Failed in \"$CST_OUTPUT_INFO\" data"
			( read THE_DATE || exit; touch --date="$THE_DATE" "$CST_OUTPUT_INFO" ) || die "Receiving snapshot \"$CST_RECEIVE_SNAPSHOT_NUMBER\": Failed in \"$CST_OUTPUT_INFO\" timestamp"
		fi

		# Answer with received UUID, to get the protocol going again...
		CST_SNAPSHOT_NUMBER="$CST_RECEIVE_SNAPSHOT_NUMBER"
		protomsg_receivedUUID || die "Error in sending our next protocol message \"receivedUUID\" (after \"receive\"), aborting"
		;;
	*)
		die "Invalid other side message: Unrecognized message type \"$CST_OTHER_WHAT\""
		;;
	esac
	[ -n "$CST_BREAK" ] && break
done

if [ -z "$CST_GOT_END" ]
then
	# (Use warn although this is normal output, to not confuse the message protocol...)
	warn "Failing main operation. Received:${CST_RECEIVED_SNAPNUMS:- (none)}"

	die "Other side terminated without sending proper end message! Aborting (potential) post-operation..."
else
	# (Use warn although this is normal output, to not confuse the message protocol...)
	warn "Finished main operation. Received:${CST_RECEIVED_SNAPNUMS:- (none)}"
fi


# Post-operation. (As at the ~end of replicate-send.)
if [ -n "$CST_RECEIVED_SNAPNUMS" ]
then
	# Update the active subvol with the last received snapshot,
	# hanging the .snapshots subvol into there.
	"$CST_DIR/replace-active" "$CST_OUTPUT_SUBVOL" "$CST_SNAPSHOT_NUMBER" >&2 || die "Post-operation: Failed to update output active subvolume at \"$CST_OUTPUT_SUBVOL\""
	# ^ >&2 redirects the status message from stdout (where our
	#   message protocol is running over) to stderr.
fi


exit 0
